<script lang="ts">
    import { setContext } from "svelte";
    import { type GeraltContext } from "$lib/types.svelte";
    import { gearState } from '$lib/gearState.svelte';
    import { skillState } from "$lib/skillState.svelte";
    import { mutagenState } from "../mutagenState.svelte";
    import { mutationState } from "$lib/mutationState.svelte";
    import UiAbilityBank from "../UiAbilityBank.svelte";
    import UiGearKit from '../UiGearKit.svelte';
    import UiAbilityKit from "../UiAbilityKit.svelte";
    import UiStats from "../UiStats.svelte";
    
    setContext<GeraltContext>("geralt", {
        gearState,
        mutagenState,
        mutationState,
        skillState,
    });
</script>



<main>
    <div class="frameKits">
        <UiAbilityBank/>
        <UiAbilityKit/>
    </div>

    <div class="gearAndStats">
        <UiGearKit/>
        <div class="statsWrapper">
            <UiStats/>
        </div>
    </div>
</main>



<style lang="scss">
    $lr-subdivision-0:   1 / 52;
    $lr-subdivision-1:   2 / 52;
    $lr-subdivision-2:   3 / 52;
    $lr-subdivision-3:   4 / 52;
    $lr-subdivision-4:   5 / 52;
    $lr-subdivision-5:   6 / 52;
    $lr-subdivision-6:   7 / 52;
    $lr-subdivision-7:   8 / 52;
    $lr-subdivision-8:   9 / 52;
    $lr-subdivision-9:  10 / 52;
    $lr-subdivision-10: 11 / 52;
    $lr-subdivision-11: 12 / 52;
    $lr-subdivision-12: 13 / 52;
    $lr-subdivision-13: 14 / 52;
    $lr-subdivision-14: 15 / 52;
    $lr-subdivision-15: 16 / 52;
    $lr-subdivision-16: 17 / 52;
    $lr-subdivision-17: 18 / 52;
    $lr-subdivision-18: 19 / 52;
    $lr-subdivision-19: 20 / 52;
    $lr-subdivision-20: 21 / 52;
    $lr-subdivision-21: 22 / 52;
    $lr-subdivision-22: 23 / 52;
    $lr-subdivision-23: 24 / 52;
    $lr-subdivision-24: 25 / 52;
    $lr-subdivision-25: 26 / 52;
    $lr-subdivision-26: 27 / 52;
    $lr-subdivision-27: 28 / 52;
    $lr-subdivision-28: 29 / 52;
    $lr-subdivision-29: 30 / 52;
    $lr-subdivision-30: 31 / 52;
    $lr-subdivision-31: 32 / 52;
    $lr-subdivision-32: 33 / 52;
    $lr-subdivision-33: 34 / 52;
    $lr-subdivision-34: 35 / 52;
    $lr-subdivision-35: 36 / 52;
    $lr-subdivision-36: 37 / 52;
    $lr-subdivision-37: 38 / 52;
    $lr-subdivision-38: 39 / 52;
    $lr-subdivision-39: 40 / 52;
    $lr-subdivision-40: 41 / 52;
    $lr-subdivision-41: 42 / 52;
    $lr-subdivision-42: 43 / 52;
    $lr-subdivision-43: 44 / 52;
    $lr-subdivision-44: 45 / 52;
    $lr-subdivision-45: 46 / 52;
    $lr-subdivision-46: 47 / 52;
    $lr-subdivision-47: 48 / 52;
    $lr-subdivision-48: 49 / 52;
    $lr-subdivision-49: 50 / 52;
    $lr-subdivision-50: 51 / 52;

    $lr-vertex: sqrt(1 / 2); // relative lightness point [0-1] where chroma is max
    $lr-min: 0;
    $lr-max: 1;
    $lr-range: $lr-max - $lr-min;
    $lr-vertex-subdivision: $lr-subdivision-32; // coordinated with a chroma apex at lr-subdivision-32
    
    @function calculate-lr($lr-subdivision) {
        $lr-p: log(($lr-vertex - $lr-min) / $lr-range, $lr-vertex-subdivision);
        @return calc($lr-min + ($lr-range * pow($lr-subdivision, $lr-p)));
    }

    @function lr-to-l($lr) {
        $l-k1: 0.206;
        $l-k2: 0.03;
        $l-k3: calc((1 + $l-k1) / (1 + $l-k2));
        $l: calc(($lr * ($lr + $l-k1)) / ($l-k3 * ($lr + $l-k2)));
        @return $l;
    }
    
    $chroma-max: 0.147;                           // [0-1] max chroma safe within all hues of chosen palette
    $anchor-lr: calculate-lr($lr-subdivision-10); // [0-1] anchor point color's lightness (relative to white)
    $anchor-cr: 0.52;                             // [0-1] anchor point color's max chroma at $anchor-lr (relative to $chroma-max)

    @function calculate-chroma-limit($lr) {
        $chroma-b: log($anchor-cr, $anchor-lr / $lr-vertex);
        $isBright: $lr-vertex > $lr;
        $c-ratio: if(
            sass($isBright): pow($lr / $lr-vertex, $chroma-b);
            else: sqrt(abs(((1 - $lr) / (1 - $lr-vertex)) * (1 - pow(abs(($lr - $lr-vertex) / (1 - $lr-vertex)), $chroma-b))));
        );
        $chroma-limit: $chroma-max * $c-ratio;
        @return $chroma-limit;
    }

    @function calculate-color($lr-subdivision, $saturation-mult, $hue) {
        $lr: calculate-lr($lr-subdivision);
        $lightness: lr-to-l($lr);
        $chroma: calculate-chroma-limit($lr) * $saturation-mult;
        @return oklch($lightness $chroma $hue);
    }

    $color-grey-0:  calculate-color($lr-subdivision-0,  0, 0);
    $color-grey-1:  calculate-color($lr-subdivision-1,  0, 0);
    $color-grey-2:  calculate-color($lr-subdivision-2,  0, 0);
    $color-grey-3:  calculate-color($lr-subdivision-3,  0, 0);
    $color-grey-4:  calculate-color($lr-subdivision-4,  0, 0);
    $color-grey-5:  calculate-color($lr-subdivision-5,  0, 0);
    $color-grey-6:  calculate-color($lr-subdivision-6,  0, 0);
    $color-grey-7:  calculate-color($lr-subdivision-7,  0, 0);
    $color-grey-8:  calculate-color($lr-subdivision-8,  0, 0);
    $color-grey-9:  calculate-color($lr-subdivision-9,  0, 0);
    $color-grey-10: calculate-color($lr-subdivision-10, 0, 0);
    $color-grey-11: calculate-color($lr-subdivision-11, 0, 0);
    $color-grey-12: calculate-color($lr-subdivision-12, 0, 0);
    $color-grey-13: calculate-color($lr-subdivision-13, 0, 0);
    $color-grey-14: calculate-color($lr-subdivision-14, 0, 0);
    $color-grey-15: calculate-color($lr-subdivision-15, 0, 0);
    $color-grey-16: calculate-color($lr-subdivision-16, 0, 0);
    $color-grey-17: calculate-color($lr-subdivision-17, 0, 0);
    $color-grey-18: calculate-color($lr-subdivision-18, 0, 0);
    $color-grey-19: calculate-color($lr-subdivision-19, 0, 0);
    $color-grey-20: calculate-color($lr-subdivision-20, 0, 0);
    $color-grey-21: calculate-color($lr-subdivision-21, 0, 0);
    $color-grey-22: calculate-color($lr-subdivision-22, 0, 0);
    $color-grey-23: calculate-color($lr-subdivision-23, 0, 0);
    $color-grey-24: calculate-color($lr-subdivision-24, 0, 0);
    $color-grey-25: calculate-color($lr-subdivision-25, 0, 0);
    $color-grey-26: calculate-color($lr-subdivision-26, 0, 0);
    $color-grey-27: calculate-color($lr-subdivision-27, 0, 0);
    $color-grey-28: calculate-color($lr-subdivision-28, 0, 0);
    $color-grey-29: calculate-color($lr-subdivision-29, 0, 0);
    $color-grey-30: calculate-color($lr-subdivision-30, 0, 0);
    $color-grey-31: calculate-color($lr-subdivision-31, 0, 0);
    $color-grey-32: calculate-color($lr-subdivision-32, 0, 0);
    $color-grey-33: calculate-color($lr-subdivision-33, 0, 0);
    $color-grey-34: calculate-color($lr-subdivision-34, 0, 0);
    $color-grey-35: calculate-color($lr-subdivision-35, 0, 0);
    $color-grey-36: calculate-color($lr-subdivision-36, 0, 0);
    $color-grey-37: calculate-color($lr-subdivision-37, 0, 0);
    $color-grey-38: calculate-color($lr-subdivision-38, 0, 0);
    $color-grey-39: calculate-color($lr-subdivision-39, 0, 0);
    $color-grey-40: calculate-color($lr-subdivision-40, 0, 0);
    $color-grey-41: calculate-color($lr-subdivision-41, 0, 0);
    $color-grey-42: calculate-color($lr-subdivision-42, 0, 0);
    $color-grey-43: calculate-color($lr-subdivision-43, 0, 0);
    $color-grey-44: calculate-color($lr-subdivision-44, 0, 0);
    $color-grey-45: calculate-color($lr-subdivision-45, 0, 0);
    $color-grey-46: calculate-color($lr-subdivision-46, 0, 0);
    $color-grey-47: calculate-color($lr-subdivision-47, 0, 0);
    $color-grey-48: calculate-color($lr-subdivision-48, 0, 0);
    $color-grey-49: calculate-color($lr-subdivision-49, 0, 0);
    $color-grey-50: calculate-color($lr-subdivision-50, 0, 0);

    $hue-silver: 230.8125;
    $color-silver-0:  calculate-color($lr-subdivision-0,  1, $hue-silver);
    $color-silver-1:  calculate-color($lr-subdivision-1,  1, $hue-silver);
    $color-silver-2:  calculate-color($lr-subdivision-2,  1, $hue-silver);
    $color-silver-3:  calculate-color($lr-subdivision-3,  1, $hue-silver);
    $color-silver-4:  calculate-color($lr-subdivision-4,  1, $hue-silver);
    $color-silver-5:  calculate-color($lr-subdivision-5,  1, $hue-silver);
    $color-silver-6:  calculate-color($lr-subdivision-6,  1, $hue-silver);
    $color-silver-7:  calculate-color($lr-subdivision-7,  1, $hue-silver);
    $color-silver-8:  calculate-color($lr-subdivision-8,  1, $hue-silver);
    $color-silver-9:  calculate-color($lr-subdivision-9,  1, $hue-silver);
    $color-silver-10: calculate-color($lr-subdivision-10, 1, $hue-silver);
    $color-silver-11: calculate-color($lr-subdivision-11, 1, $hue-silver);
    $color-silver-12: calculate-color($lr-subdivision-12, 1, $hue-silver);
    $color-silver-13: calculate-color($lr-subdivision-13, 1, $hue-silver);
    $color-silver-14: calculate-color($lr-subdivision-14, 1, $hue-silver);
    $color-silver-15: calculate-color($lr-subdivision-15, 1, $hue-silver);
    $color-silver-16: calculate-color($lr-subdivision-16, 1, $hue-silver);
    $color-silver-17: calculate-color($lr-subdivision-17, 1, $hue-silver);
    $color-silver-18: calculate-color($lr-subdivision-18, 1, $hue-silver);
    $color-silver-19: calculate-color($lr-subdivision-19, 1, $hue-silver);
    $color-silver-20: calculate-color($lr-subdivision-20, 1, $hue-silver);
    $color-silver-21: calculate-color($lr-subdivision-21, 1, $hue-silver);
    $color-silver-22: calculate-color($lr-subdivision-22, 1, $hue-silver);
    $color-silver-23: calculate-color($lr-subdivision-23, 1, $hue-silver);
    $color-silver-24: calculate-color($lr-subdivision-24, 1, $hue-silver);
    $color-silver-25: calculate-color($lr-subdivision-25, 1, $hue-silver);
    $color-silver-26: calculate-color($lr-subdivision-26, 1, $hue-silver);
    $color-silver-27: calculate-color($lr-subdivision-27, 1, $hue-silver);
    $color-silver-28: calculate-color($lr-subdivision-28, 1, $hue-silver);
    $color-silver-29: calculate-color($lr-subdivision-29, 1, $hue-silver);
    $color-silver-30: calculate-color($lr-subdivision-30, 1, $hue-silver);
    $color-silver-31: calculate-color($lr-subdivision-31, 1, $hue-silver);
    $color-silver-32: calculate-color($lr-subdivision-32, 1, $hue-silver);
    $color-silver-33: calculate-color($lr-subdivision-33, 1, $hue-silver);
    $color-silver-34: calculate-color($lr-subdivision-34, 1, $hue-silver);
    $color-silver-35: calculate-color($lr-subdivision-35, 1, $hue-silver);
    $color-silver-36: calculate-color($lr-subdivision-36, 1, $hue-silver);
    $color-silver-37: calculate-color($lr-subdivision-37, 1, $hue-silver);
    $color-silver-38: calculate-color($lr-subdivision-38, 1, $hue-silver);
    $color-silver-39: calculate-color($lr-subdivision-39, 1, $hue-silver);
    $color-silver-40: calculate-color($lr-subdivision-40, 1, $hue-silver);
    $color-silver-41: calculate-color($lr-subdivision-41, 1, $hue-silver);
    $color-silver-42: calculate-color($lr-subdivision-42, 1, $hue-silver);
    $color-silver-43: calculate-color($lr-subdivision-43, 1, $hue-silver);
    $color-silver-44: calculate-color($lr-subdivision-44, 1, $hue-silver);
    $color-silver-45: calculate-color($lr-subdivision-45, 1, $hue-silver);
    $color-silver-46: calculate-color($lr-subdivision-46, 1, $hue-silver);
    $color-silver-47: calculate-color($lr-subdivision-47, 1, $hue-silver);
    $color-silver-48: calculate-color($lr-subdivision-48, 1, $hue-silver);
    $color-silver-49: calculate-color($lr-subdivision-49, 1, $hue-silver);
    $color-silver-50: calculate-color($lr-subdivision-50, 1, $hue-silver);

    $hue-steel: 50.8125;
    $color-steel-0:  calculate-color($lr-subdivision-0,  1, $hue-steel);
    $color-steel-1:  calculate-color($lr-subdivision-1,  1, $hue-steel);
    $color-steel-2:  calculate-color($lr-subdivision-2,  1, $hue-steel);
    $color-steel-3:  calculate-color($lr-subdivision-3,  1, $hue-steel);
    $color-steel-4:  calculate-color($lr-subdivision-4,  1, $hue-steel);
    $color-steel-5:  calculate-color($lr-subdivision-5,  1, $hue-steel);
    $color-steel-6:  calculate-color($lr-subdivision-6,  1, $hue-steel);
    $color-steel-7:  calculate-color($lr-subdivision-7,  1, $hue-steel);
    $color-steel-8:  calculate-color($lr-subdivision-8,  1, $hue-steel);
    $color-steel-9:  calculate-color($lr-subdivision-9,  1, $hue-steel);
    $color-steel-10: calculate-color($lr-subdivision-10, 1, $hue-steel);
    $color-steel-11: calculate-color($lr-subdivision-11, 1, $hue-steel);
    $color-steel-12: calculate-color($lr-subdivision-12, 1, $hue-steel);
    $color-steel-13: calculate-color($lr-subdivision-13, 1, $hue-steel);
    $color-steel-14: calculate-color($lr-subdivision-14, 1, $hue-steel);
    $color-steel-15: calculate-color($lr-subdivision-15, 1, $hue-steel);
    $color-steel-16: calculate-color($lr-subdivision-16, 1, $hue-steel);
    $color-steel-17: calculate-color($lr-subdivision-17, 1, $hue-steel);
    $color-steel-18: calculate-color($lr-subdivision-18, 1, $hue-steel);
    $color-steel-19: calculate-color($lr-subdivision-19, 1, $hue-steel);
    $color-steel-20: calculate-color($lr-subdivision-20, 1, $hue-steel);
    $color-steel-21: calculate-color($lr-subdivision-21, 1, $hue-steel);
    $color-steel-22: calculate-color($lr-subdivision-22, 1, $hue-steel);
    $color-steel-23: calculate-color($lr-subdivision-23, 1, $hue-steel);
    $color-steel-24: calculate-color($lr-subdivision-24, 1, $hue-steel);
    $color-steel-25: calculate-color($lr-subdivision-25, 1, $hue-steel);
    $color-steel-26: calculate-color($lr-subdivision-26, 1, $hue-steel);
    $color-steel-27: calculate-color($lr-subdivision-27, 1, $hue-steel);
    $color-steel-28: calculate-color($lr-subdivision-28, 1, $hue-steel);
    $color-steel-29: calculate-color($lr-subdivision-29, 1, $hue-steel);
    $color-steel-30: calculate-color($lr-subdivision-30, 1, $hue-steel);
    $color-steel-31: calculate-color($lr-subdivision-31, 1, $hue-steel);
    $color-steel-32: calculate-color($lr-subdivision-32, 1, $hue-steel);
    $color-steel-33: calculate-color($lr-subdivision-33, 1, $hue-steel);
    $color-steel-34: calculate-color($lr-subdivision-34, 1, $hue-steel);
    $color-steel-35: calculate-color($lr-subdivision-35, 1, $hue-steel);
    $color-steel-36: calculate-color($lr-subdivision-36, 1, $hue-steel);
    $color-steel-37: calculate-color($lr-subdivision-37, 1, $hue-steel);
    $color-steel-38: calculate-color($lr-subdivision-38, 1, $hue-steel);
    $color-steel-39: calculate-color($lr-subdivision-39, 1, $hue-steel);
    $color-steel-40: calculate-color($lr-subdivision-40, 1, $hue-steel);
    $color-steel-41: calculate-color($lr-subdivision-41, 1, $hue-steel);
    $color-steel-42: calculate-color($lr-subdivision-42, 1, $hue-steel);
    $color-steel-43: calculate-color($lr-subdivision-43, 1, $hue-steel);
    $color-steel-44: calculate-color($lr-subdivision-44, 1, $hue-steel);
    $color-steel-45: calculate-color($lr-subdivision-45, 1, $hue-steel);
    $color-steel-46: calculate-color($lr-subdivision-46, 1, $hue-steel);
    $color-steel-47: calculate-color($lr-subdivision-47, 1, $hue-steel);
    $color-steel-48: calculate-color($lr-subdivision-48, 1, $hue-steel);
    $color-steel-49: calculate-color($lr-subdivision-49, 1, $hue-steel);
    $color-steel-50: calculate-color($lr-subdivision-50, 1, $hue-steel);

    $hue-combat: 23;
    $color-combat-0:  calculate-color($lr-subdivision-0,  1, $hue-combat);
    $color-combat-1:  calculate-color($lr-subdivision-1,  1, $hue-combat);
    $color-combat-2:  calculate-color($lr-subdivision-2,  1, $hue-combat);
    $color-combat-3:  calculate-color($lr-subdivision-3,  1, $hue-combat);
    $color-combat-4:  calculate-color($lr-subdivision-4,  1, $hue-combat);
    $color-combat-5:  calculate-color($lr-subdivision-5,  1, $hue-combat);
    $color-combat-6:  calculate-color($lr-subdivision-6,  1, $hue-combat);
    $color-combat-7:  calculate-color($lr-subdivision-7,  1, $hue-combat);
    $color-combat-8:  calculate-color($lr-subdivision-8,  1, $hue-combat);
    $color-combat-9:  calculate-color($lr-subdivision-9,  1, $hue-combat);
    $color-combat-10: calculate-color($lr-subdivision-10, 1, $hue-combat);
    $color-combat-11: calculate-color($lr-subdivision-11, 1, $hue-combat);
    $color-combat-12: calculate-color($lr-subdivision-12, 1, $hue-combat);
    $color-combat-13: calculate-color($lr-subdivision-13, 1, $hue-combat);
    $color-combat-14: calculate-color($lr-subdivision-14, 1, $hue-combat);
    $color-combat-15: calculate-color($lr-subdivision-15, 1, $hue-combat);
    $color-combat-16: calculate-color($lr-subdivision-16, 1, $hue-combat);
    $color-combat-17: calculate-color($lr-subdivision-17, 1, $hue-combat);
    $color-combat-18: calculate-color($lr-subdivision-18, 1, $hue-combat);
    $color-combat-19: calculate-color($lr-subdivision-19, 1, $hue-combat);
    $color-combat-20: calculate-color($lr-subdivision-20, 1, $hue-combat);
    $color-combat-21: calculate-color($lr-subdivision-21, 1, $hue-combat);
    $color-combat-22: calculate-color($lr-subdivision-22, 1, $hue-combat);
    $color-combat-23: calculate-color($lr-subdivision-23, 1, $hue-combat);
    $color-combat-24: calculate-color($lr-subdivision-24, 1, $hue-combat);
    $color-combat-25: calculate-color($lr-subdivision-25, 1, $hue-combat);
    $color-combat-26: calculate-color($lr-subdivision-26, 1, $hue-combat);
    $color-combat-27: calculate-color($lr-subdivision-27, 1, $hue-combat);
    $color-combat-28: calculate-color($lr-subdivision-28, 1, $hue-combat);
    $color-combat-29: calculate-color($lr-subdivision-29, 1, $hue-combat);
    $color-combat-30: calculate-color($lr-subdivision-30, 1, $hue-combat);
    $color-combat-31: calculate-color($lr-subdivision-31, 1, $hue-combat);
    $color-combat-32: calculate-color($lr-subdivision-32, 1, $hue-combat);
    $color-combat-33: calculate-color($lr-subdivision-33, 1, $hue-combat);
    $color-combat-34: calculate-color($lr-subdivision-34, 1, $hue-combat);
    $color-combat-35: calculate-color($lr-subdivision-35, 1, $hue-combat);
    $color-combat-36: calculate-color($lr-subdivision-36, 1, $hue-combat);
    $color-combat-37: calculate-color($lr-subdivision-37, 1, $hue-combat);
    $color-combat-38: calculate-color($lr-subdivision-38, 1, $hue-combat);
    $color-combat-39: calculate-color($lr-subdivision-39, 1, $hue-combat);
    $color-combat-40: calculate-color($lr-subdivision-40, 1, $hue-combat);
    $color-combat-41: calculate-color($lr-subdivision-41, 1, $hue-combat);
    $color-combat-42: calculate-color($lr-subdivision-42, 1, $hue-combat);
    $color-combat-43: calculate-color($lr-subdivision-43, 1, $hue-combat);
    $color-combat-44: calculate-color($lr-subdivision-44, 1, $hue-combat);
    $color-combat-45: calculate-color($lr-subdivision-45, 1, $hue-combat);
    $color-combat-46: calculate-color($lr-subdivision-46, 1, $hue-combat);
    $color-combat-47: calculate-color($lr-subdivision-47, 1, $hue-combat);
    $color-combat-48: calculate-color($lr-subdivision-48, 1, $hue-combat);
    $color-combat-49: calculate-color($lr-subdivision-49, 1, $hue-combat);
    $color-combat-50: calculate-color($lr-subdivision-50, 1, $hue-combat);

    $hue-signs: 245.5;
    $color-signs-0:  calculate-color($lr-subdivision-0,  1, $hue-signs);
    $color-signs-1:  calculate-color($lr-subdivision-1,  1, $hue-signs);
    $color-signs-2:  calculate-color($lr-subdivision-2,  1, $hue-signs);
    $color-signs-3:  calculate-color($lr-subdivision-3,  1, $hue-signs);
    $color-signs-4:  calculate-color($lr-subdivision-4,  1, $hue-signs);
    $color-signs-5:  calculate-color($lr-subdivision-5,  1, $hue-signs);
    $color-signs-6:  calculate-color($lr-subdivision-6,  1, $hue-signs);
    $color-signs-7:  calculate-color($lr-subdivision-7,  1, $hue-signs);
    $color-signs-8:  calculate-color($lr-subdivision-8,  1, $hue-signs);
    $color-signs-9:  calculate-color($lr-subdivision-9,  1, $hue-signs);
    $color-signs-10: calculate-color($lr-subdivision-10, 1, $hue-signs);
    $color-signs-11: calculate-color($lr-subdivision-11, 1, $hue-signs);
    $color-signs-12: calculate-color($lr-subdivision-12, 1, $hue-signs);
    $color-signs-13: calculate-color($lr-subdivision-13, 1, $hue-signs);
    $color-signs-14: calculate-color($lr-subdivision-14, 1, $hue-signs);
    $color-signs-15: calculate-color($lr-subdivision-15, 1, $hue-signs);
    $color-signs-16: calculate-color($lr-subdivision-16, 1, $hue-signs);
    $color-signs-17: calculate-color($lr-subdivision-17, 1, $hue-signs);
    $color-signs-18: calculate-color($lr-subdivision-18, 1, $hue-signs);
    $color-signs-19: calculate-color($lr-subdivision-19, 1, $hue-signs);
    $color-signs-20: calculate-color($lr-subdivision-20, 1, $hue-signs);
    $color-signs-21: calculate-color($lr-subdivision-21, 1, $hue-signs);
    $color-signs-22: calculate-color($lr-subdivision-22, 1, $hue-signs);
    $color-signs-23: calculate-color($lr-subdivision-23, 1, $hue-signs);
    $color-signs-24: calculate-color($lr-subdivision-24, 1, $hue-signs);
    $color-signs-25: calculate-color($lr-subdivision-25, 1, $hue-signs);
    $color-signs-26: calculate-color($lr-subdivision-26, 1, $hue-signs);
    $color-signs-27: calculate-color($lr-subdivision-27, 1, $hue-signs);
    $color-signs-28: calculate-color($lr-subdivision-28, 1, $hue-signs);
    $color-signs-29: calculate-color($lr-subdivision-29, 1, $hue-signs);
    $color-signs-30: calculate-color($lr-subdivision-30, 1, $hue-signs);
    $color-signs-31: calculate-color($lr-subdivision-31, 1, $hue-signs);
    $color-signs-32: calculate-color($lr-subdivision-32, 1, $hue-signs);
    $color-signs-33: calculate-color($lr-subdivision-33, 1, $hue-signs);
    $color-signs-34: calculate-color($lr-subdivision-34, 1, $hue-signs);
    $color-signs-35: calculate-color($lr-subdivision-35, 1, $hue-signs);
    $color-signs-36: calculate-color($lr-subdivision-36, 1, $hue-signs);
    $color-signs-37: calculate-color($lr-subdivision-37, 1, $hue-signs);
    $color-signs-38: calculate-color($lr-subdivision-38, 1, $hue-signs);
    $color-signs-39: calculate-color($lr-subdivision-39, 1, $hue-signs);
    $color-signs-40: calculate-color($lr-subdivision-40, 1, $hue-signs);
    $color-signs-41: calculate-color($lr-subdivision-41, 1, $hue-signs);
    $color-signs-42: calculate-color($lr-subdivision-42, 1, $hue-signs);
    $color-signs-43: calculate-color($lr-subdivision-43, 1, $hue-signs);
    $color-signs-44: calculate-color($lr-subdivision-44, 1, $hue-signs);
    $color-signs-45: calculate-color($lr-subdivision-45, 1, $hue-signs);
    $color-signs-46: calculate-color($lr-subdivision-46, 1, $hue-signs);
    $color-signs-47: calculate-color($lr-subdivision-47, 1, $hue-signs);
    $color-signs-48: calculate-color($lr-subdivision-48, 1, $hue-signs);
    $color-signs-49: calculate-color($lr-subdivision-49, 1, $hue-signs);
    $color-signs-50: calculate-color($lr-subdivision-50, 1, $hue-signs);

    $hue-alchemy: 134.25;
    $color-alchemy-0:  calculate-color($lr-subdivision-0,  1, $hue-alchemy);
    $color-alchemy-1:  calculate-color($lr-subdivision-1,  1, $hue-alchemy);
    $color-alchemy-2:  calculate-color($lr-subdivision-2,  1, $hue-alchemy);
    $color-alchemy-3:  calculate-color($lr-subdivision-3,  1, $hue-alchemy);
    $color-alchemy-4:  calculate-color($lr-subdivision-4,  1, $hue-alchemy);
    $color-alchemy-5:  calculate-color($lr-subdivision-5,  1, $hue-alchemy);
    $color-alchemy-6:  calculate-color($lr-subdivision-6,  1, $hue-alchemy);
    $color-alchemy-7:  calculate-color($lr-subdivision-7,  1, $hue-alchemy);
    $color-alchemy-8:  calculate-color($lr-subdivision-8,  1, $hue-alchemy);
    $color-alchemy-9:  calculate-color($lr-subdivision-9,  1, $hue-alchemy);
    $color-alchemy-10: calculate-color($lr-subdivision-10, 1, $hue-alchemy);
    $color-alchemy-11: calculate-color($lr-subdivision-11, 1, $hue-alchemy);
    $color-alchemy-12: calculate-color($lr-subdivision-12, 1, $hue-alchemy);
    $color-alchemy-13: calculate-color($lr-subdivision-13, 1, $hue-alchemy);
    $color-alchemy-14: calculate-color($lr-subdivision-14, 1, $hue-alchemy);
    $color-alchemy-15: calculate-color($lr-subdivision-15, 1, $hue-alchemy);
    $color-alchemy-16: calculate-color($lr-subdivision-16, 1, $hue-alchemy);
    $color-alchemy-17: calculate-color($lr-subdivision-17, 1, $hue-alchemy);
    $color-alchemy-18: calculate-color($lr-subdivision-18, 1, $hue-alchemy);
    $color-alchemy-19: calculate-color($lr-subdivision-19, 1, $hue-alchemy);
    $color-alchemy-20: calculate-color($lr-subdivision-20, 1, $hue-alchemy);
    $color-alchemy-21: calculate-color($lr-subdivision-21, 1, $hue-alchemy);
    $color-alchemy-22: calculate-color($lr-subdivision-22, 1, $hue-alchemy);
    $color-alchemy-23: calculate-color($lr-subdivision-23, 1, $hue-alchemy);
    $color-alchemy-24: calculate-color($lr-subdivision-24, 1, $hue-alchemy);
    $color-alchemy-25: calculate-color($lr-subdivision-25, 1, $hue-alchemy);
    $color-alchemy-26: calculate-color($lr-subdivision-26, 1, $hue-alchemy);
    $color-alchemy-27: calculate-color($lr-subdivision-27, 1, $hue-alchemy);
    $color-alchemy-28: calculate-color($lr-subdivision-28, 1, $hue-alchemy);
    $color-alchemy-29: calculate-color($lr-subdivision-29, 1, $hue-alchemy);
    $color-alchemy-30: calculate-color($lr-subdivision-30, 1, $hue-alchemy);
    $color-alchemy-31: calculate-color($lr-subdivision-31, 1, $hue-alchemy);
    $color-alchemy-32: calculate-color($lr-subdivision-32, 1, $hue-alchemy);
    $color-alchemy-33: calculate-color($lr-subdivision-33, 1, $hue-alchemy);
    $color-alchemy-34: calculate-color($lr-subdivision-34, 1, $hue-alchemy);
    $color-alchemy-35: calculate-color($lr-subdivision-35, 1, $hue-alchemy);
    $color-alchemy-36: calculate-color($lr-subdivision-36, 1, $hue-alchemy);
    $color-alchemy-37: calculate-color($lr-subdivision-37, 1, $hue-alchemy);
    $color-alchemy-38: calculate-color($lr-subdivision-38, 1, $hue-alchemy);
    $color-alchemy-39: calculate-color($lr-subdivision-39, 1, $hue-alchemy);
    $color-alchemy-40: calculate-color($lr-subdivision-40, 1, $hue-alchemy);
    $color-alchemy-41: calculate-color($lr-subdivision-41, 1, $hue-alchemy);
    $color-alchemy-42: calculate-color($lr-subdivision-42, 1, $hue-alchemy);
    $color-alchemy-43: calculate-color($lr-subdivision-43, 1, $hue-alchemy);
    $color-alchemy-44: calculate-color($lr-subdivision-44, 1, $hue-alchemy);
    $color-alchemy-45: calculate-color($lr-subdivision-45, 1, $hue-alchemy);
    $color-alchemy-46: calculate-color($lr-subdivision-46, 1, $hue-alchemy);
    $color-alchemy-47: calculate-color($lr-subdivision-47, 1, $hue-alchemy);
    $color-alchemy-48: calculate-color($lr-subdivision-48, 1, $hue-alchemy);
    $color-alchemy-49: calculate-color($lr-subdivision-49, 1, $hue-alchemy);
    $color-alchemy-50: calculate-color($lr-subdivision-50, 1, $hue-alchemy);

    $hue-general: 78.625;
    $color-general-0:  calculate-color($lr-subdivision-0,  1, $hue-general);
    $color-general-1:  calculate-color($lr-subdivision-1,  1, $hue-general);
    $color-general-2:  calculate-color($lr-subdivision-2,  1, $hue-general);
    $color-general-3:  calculate-color($lr-subdivision-3,  1, $hue-general);
    $color-general-4:  calculate-color($lr-subdivision-4,  1, $hue-general);
    $color-general-5:  calculate-color($lr-subdivision-5,  1, $hue-general);
    $color-general-6:  calculate-color($lr-subdivision-6,  1, $hue-general);
    $color-general-7:  calculate-color($lr-subdivision-7,  1, $hue-general);
    $color-general-8:  calculate-color($lr-subdivision-8,  1, $hue-general);
    $color-general-9:  calculate-color($lr-subdivision-9,  1, $hue-general);
    $color-general-10: calculate-color($lr-subdivision-10, 1, $hue-general);
    $color-general-11: calculate-color($lr-subdivision-11, 1, $hue-general);
    $color-general-12: calculate-color($lr-subdivision-12, 1, $hue-general);
    $color-general-13: calculate-color($lr-subdivision-13, 1, $hue-general);
    $color-general-14: calculate-color($lr-subdivision-14, 1, $hue-general);
    $color-general-15: calculate-color($lr-subdivision-15, 1, $hue-general);
    $color-general-16: calculate-color($lr-subdivision-16, 1, $hue-general);
    $color-general-17: calculate-color($lr-subdivision-17, 1, $hue-general);
    $color-general-18: calculate-color($lr-subdivision-18, 1, $hue-general);
    $color-general-19: calculate-color($lr-subdivision-19, 1, $hue-general);
    $color-general-20: calculate-color($lr-subdivision-20, 1, $hue-general);
    $color-general-21: calculate-color($lr-subdivision-21, 1, $hue-general);
    $color-general-22: calculate-color($lr-subdivision-22, 1, $hue-general);
    $color-general-23: calculate-color($lr-subdivision-23, 1, $hue-general);
    $color-general-24: calculate-color($lr-subdivision-24, 1, $hue-general);
    $color-general-25: calculate-color($lr-subdivision-25, 1, $hue-general);
    $color-general-26: calculate-color($lr-subdivision-26, 1, $hue-general);
    $color-general-27: calculate-color($lr-subdivision-27, 1, $hue-general);
    $color-general-28: calculate-color($lr-subdivision-28, 1, $hue-general);
    $color-general-29: calculate-color($lr-subdivision-29, 1, $hue-general);
    $color-general-30: calculate-color($lr-subdivision-30, 1, $hue-general);
    $color-general-31: calculate-color($lr-subdivision-31, 1, $hue-general);
    $color-general-32: calculate-color($lr-subdivision-32, 1, $hue-general);
    $color-general-33: calculate-color($lr-subdivision-33, 1, $hue-general);
    $color-general-34: calculate-color($lr-subdivision-34, 1, $hue-general);
    $color-general-35: calculate-color($lr-subdivision-35, 1, $hue-general);
    $color-general-36: calculate-color($lr-subdivision-36, 1, $hue-general);
    $color-general-37: calculate-color($lr-subdivision-37, 1, $hue-general);
    $color-general-38: calculate-color($lr-subdivision-38, 1, $hue-general);
    $color-general-39: calculate-color($lr-subdivision-39, 1, $hue-general);
    $color-general-40: calculate-color($lr-subdivision-40, 1, $hue-general);
    $color-general-41: calculate-color($lr-subdivision-41, 1, $hue-general);
    $color-general-42: calculate-color($lr-subdivision-42, 1, $hue-general);
    $color-general-43: calculate-color($lr-subdivision-43, 1, $hue-general);
    $color-general-44: calculate-color($lr-subdivision-44, 1, $hue-general);
    $color-general-45: calculate-color($lr-subdivision-45, 1, $hue-general);
    $color-general-46: calculate-color($lr-subdivision-46, 1, $hue-general);
    $color-general-47: calculate-color($lr-subdivision-47, 1, $hue-general);
    $color-general-48: calculate-color($lr-subdivision-48, 1, $hue-general);
    $color-general-49: calculate-color($lr-subdivision-49, 1, $hue-general);
    $color-general-50: calculate-color($lr-subdivision-50, 1, $hue-general);

    $hue-mutations: 300; // randomly chosen; to be decided later
    $color-mutations-0:  calculate-color($lr-subdivision-0,  1, $hue-mutations);
    $color-mutations-1:  calculate-color($lr-subdivision-1,  1, $hue-mutations);
    $color-mutations-2:  calculate-color($lr-subdivision-2,  1, $hue-mutations);
    $color-mutations-3:  calculate-color($lr-subdivision-3,  1, $hue-mutations);
    $color-mutations-4:  calculate-color($lr-subdivision-4,  1, $hue-mutations);
    $color-mutations-5:  calculate-color($lr-subdivision-5,  1, $hue-mutations);
    $color-mutations-6:  calculate-color($lr-subdivision-6,  1, $hue-mutations);
    $color-mutations-7:  calculate-color($lr-subdivision-7,  1, $hue-mutations);
    $color-mutations-8:  calculate-color($lr-subdivision-8,  1, $hue-mutations);
    $color-mutations-9:  calculate-color($lr-subdivision-9,  1, $hue-mutations);
    $color-mutations-10: calculate-color($lr-subdivision-10, 1, $hue-mutations);
    $color-mutations-11: calculate-color($lr-subdivision-11, 1, $hue-mutations);
    $color-mutations-12: calculate-color($lr-subdivision-12, 1, $hue-mutations);
    $color-mutations-13: calculate-color($lr-subdivision-13, 1, $hue-mutations);
    $color-mutations-14: calculate-color($lr-subdivision-14, 1, $hue-mutations);
    $color-mutations-15: calculate-color($lr-subdivision-15, 1, $hue-mutations);
    $color-mutations-16: calculate-color($lr-subdivision-16, 1, $hue-mutations);
    $color-mutations-17: calculate-color($lr-subdivision-17, 1, $hue-mutations);
    $color-mutations-18: calculate-color($lr-subdivision-18, 1, $hue-mutations);
    $color-mutations-19: calculate-color($lr-subdivision-19, 1, $hue-mutations);
    $color-mutations-20: calculate-color($lr-subdivision-20, 1, $hue-mutations);
    $color-mutations-21: calculate-color($lr-subdivision-21, 1, $hue-mutations);
    $color-mutations-22: calculate-color($lr-subdivision-22, 1, $hue-mutations);
    $color-mutations-23: calculate-color($lr-subdivision-23, 1, $hue-mutations);
    $color-mutations-24: calculate-color($lr-subdivision-24, 1, $hue-mutations);
    $color-mutations-25: calculate-color($lr-subdivision-25, 1, $hue-mutations);
    $color-mutations-26: calculate-color($lr-subdivision-26, 1, $hue-mutations);
    $color-mutations-27: calculate-color($lr-subdivision-27, 1, $hue-mutations);
    $color-mutations-28: calculate-color($lr-subdivision-28, 1, $hue-mutations);
    $color-mutations-29: calculate-color($lr-subdivision-29, 1, $hue-mutations);
    $color-mutations-30: calculate-color($lr-subdivision-30, 1, $hue-mutations);
    $color-mutations-31: calculate-color($lr-subdivision-31, 1, $hue-mutations);
    $color-mutations-32: calculate-color($lr-subdivision-32, 1, $hue-mutations);
    $color-mutations-33: calculate-color($lr-subdivision-33, 1, $hue-mutations);
    $color-mutations-34: calculate-color($lr-subdivision-34, 1, $hue-mutations);
    $color-mutations-35: calculate-color($lr-subdivision-35, 1, $hue-mutations);
    $color-mutations-36: calculate-color($lr-subdivision-36, 1, $hue-mutations);
    $color-mutations-37: calculate-color($lr-subdivision-37, 1, $hue-mutations);
    $color-mutations-38: calculate-color($lr-subdivision-38, 1, $hue-mutations);
    $color-mutations-39: calculate-color($lr-subdivision-39, 1, $hue-mutations);
    $color-mutations-40: calculate-color($lr-subdivision-40, 1, $hue-mutations);
    $color-mutations-41: calculate-color($lr-subdivision-41, 1, $hue-mutations);
    $color-mutations-42: calculate-color($lr-subdivision-42, 1, $hue-mutations);
    $color-mutations-43: calculate-color($lr-subdivision-43, 1, $hue-mutations);
    $color-mutations-44: calculate-color($lr-subdivision-44, 1, $hue-mutations);
    $color-mutations-45: calculate-color($lr-subdivision-45, 1, $hue-mutations);
    $color-mutations-46: calculate-color($lr-subdivision-46, 1, $hue-mutations);
    $color-mutations-47: calculate-color($lr-subdivision-47, 1, $hue-mutations);
    $color-mutations-48: calculate-color($lr-subdivision-48, 1, $hue-mutations);
    $color-mutations-49: calculate-color($lr-subdivision-49, 1, $hue-mutations);
    $color-mutations-50: calculate-color($lr-subdivision-50, 1, $hue-mutations);

    main {
        /*overflow: hidden; /* Initially hide parent overflow to allow the second child to handle scrolling */
        overflow-y: hidden;
        height: 100dvh; /* Set a height for the parent to define the available space */
        display: grid;
        grid-template-columns: repeat(auto-fit, minmax(0, max-content));

        flex-flow: row wrap;
        /* align-content: center; */
        justify-content: center;
        background-color: black;
    }

    :global(body) {
        --color-grey-0:  #{$color-grey-0};
        --color-grey-1:  #{$color-grey-1};
        --color-grey-2:  #{$color-grey-2};
        --color-grey-3:  #{$color-grey-3};
        --color-grey-4:  #{$color-grey-4};
        --color-grey-5:  #{$color-grey-5};
        --color-grey-6:  #{$color-grey-6};
        --color-grey-7:  #{$color-grey-7};
        --color-grey-8:  #{$color-grey-8};
        --color-grey-9:  #{$color-grey-9};
        --color-grey-10: #{$color-grey-10};
        --color-grey-11: #{$color-grey-11};
        --color-grey-12: #{$color-grey-12};
        --color-grey-13: #{$color-grey-13};
        --color-grey-14: #{$color-grey-14};
        --color-grey-15: #{$color-grey-15};
        --color-grey-16: #{$color-grey-16};
        --color-grey-17: #{$color-grey-17};
        --color-grey-18: #{$color-grey-18};
        --color-grey-19: #{$color-grey-19};
        --color-grey-20: #{$color-grey-20};
        --color-grey-21: #{$color-grey-21};
        --color-grey-22: #{$color-grey-22};
        --color-grey-23: #{$color-grey-23};
        --color-grey-24: #{$color-grey-24};
        --color-grey-25: #{$color-grey-25};
        --color-grey-26: #{$color-grey-26};
        --color-grey-27: #{$color-grey-27};
        --color-grey-28: #{$color-grey-28};
        --color-grey-29: #{$color-grey-29};
        --color-grey-30: #{$color-grey-30};
        --color-grey-31: #{$color-grey-31};
        --color-grey-32: #{$color-grey-32};
        --color-grey-33: #{$color-grey-33};
        --color-grey-34: #{$color-grey-34};
        --color-grey-35: #{$color-grey-35};
        --color-grey-36: #{$color-grey-36};
        --color-grey-37: #{$color-grey-37};
        --color-grey-38: #{$color-grey-38};
        --color-grey-39: #{$color-grey-39};
        --color-grey-40: #{$color-grey-40};
        --color-grey-41: #{$color-grey-41};
        --color-grey-42: #{$color-grey-42};
        --color-grey-43: #{$color-grey-43};
        --color-grey-44: #{$color-grey-44};
        --color-grey-45: #{$color-grey-45};
        --color-grey-46: #{$color-grey-46};
        --color-grey-47: #{$color-grey-47};
        --color-grey-48: #{$color-grey-48};
        --color-grey-49: #{$color-grey-49};
        --color-grey-50: #{$color-grey-50};

		--color-key-0:  var(--color-grey-0);
		--color-key-1:  var(--color-grey-1);
		--color-key-2:  var(--color-grey-2);
		--color-key-3:  var(--color-grey-3);
		--color-key-4:  var(--color-grey-4);
		--color-key-5:  var(--color-grey-5);
		--color-key-6:  var(--color-grey-6);
		--color-key-7:  var(--color-grey-7);
		--color-key-8:  var(--color-grey-8);
		--color-key-9:  var(--color-grey-9);
		--color-key-10: var(--color-grey-10);
		--color-key-11: var(--color-grey-11);
		--color-key-12: var(--color-grey-12);
		--color-key-13: var(--color-grey-13);
		--color-key-14: var(--color-grey-14);
		--color-key-15: var(--color-grey-15);
		--color-key-16: var(--color-grey-16);
		--color-key-17: var(--color-grey-17);
		--color-key-18: var(--color-grey-18);
		--color-key-19: var(--color-grey-19);
		--color-key-20: var(--color-grey-20);
		--color-key-21: var(--color-grey-21);
		--color-key-22: var(--color-grey-22);
		--color-key-23: var(--color-grey-23);
		--color-key-24: var(--color-grey-24);
		--color-key-25: var(--color-grey-25);
		--color-key-26: var(--color-grey-26);
		--color-key-27: var(--color-grey-27);
		--color-key-28: var(--color-grey-28);
		--color-key-29: var(--color-grey-29);
		--color-key-30: var(--color-grey-30);
		--color-key-31: var(--color-grey-31);
		--color-key-32: var(--color-grey-32);
		--color-key-33: var(--color-grey-33);
		--color-key-34: var(--color-grey-34);
		--color-key-35: var(--color-grey-35);
		--color-key-36: var(--color-grey-36);
		--color-key-37: var(--color-grey-37);
		--color-key-38: var(--color-grey-38);
		--color-key-39: var(--color-grey-39);
		--color-key-40: var(--color-grey-40);
		--color-key-41: var(--color-grey-41);
		--color-key-42: var(--color-grey-42);
		--color-key-43: var(--color-grey-43);
		--color-key-44: var(--color-grey-44);
		--color-key-45: var(--color-grey-45);
		--color-key-46: var(--color-grey-46);
		--color-key-47: var(--color-grey-47);
		--color-key-48: var(--color-grey-48);
		--color-key-49: var(--color-grey-49);
		--color-key-50: var(--color-grey-50);

        --color-silver-0:  #{$color-silver-0};
        --color-silver-1:  #{$color-silver-1};
        --color-silver-2:  #{$color-silver-2};
        --color-silver-3:  #{$color-silver-3};
        --color-silver-4:  #{$color-silver-4};
        --color-silver-5:  #{$color-silver-5};
        --color-silver-6:  #{$color-silver-6};
        --color-silver-7:  #{$color-silver-7};
        --color-silver-8:  #{$color-silver-8};
        --color-silver-9:  #{$color-silver-9};
        --color-silver-10: #{$color-silver-10};
        --color-silver-11: #{$color-silver-11};
        --color-silver-12: #{$color-silver-12};
        --color-silver-13: #{$color-silver-13};
        --color-silver-14: #{$color-silver-14};
        --color-silver-15: #{$color-silver-15};
        --color-silver-16: #{$color-silver-16};
        --color-silver-17: #{$color-silver-17};
        --color-silver-18: #{$color-silver-18};
        --color-silver-19: #{$color-silver-19};
        --color-silver-20: #{$color-silver-20};
        --color-silver-21: #{$color-silver-21};
        --color-silver-22: #{$color-silver-22};
        --color-silver-23: #{$color-silver-23};
        --color-silver-24: #{$color-silver-24};
        --color-silver-25: #{$color-silver-25};
        --color-silver-26: #{$color-silver-26};
        --color-silver-27: #{$color-silver-27};
        --color-silver-28: #{$color-silver-28};
        --color-silver-29: #{$color-silver-29};
        --color-silver-30: #{$color-silver-30};
        --color-silver-31: #{$color-silver-31};
        --color-silver-32: #{$color-silver-32};
        --color-silver-33: #{$color-silver-33};
        --color-silver-34: #{$color-silver-34};
        --color-silver-35: #{$color-silver-35};
        --color-silver-36: #{$color-silver-36};
        --color-silver-37: #{$color-silver-37};
        --color-silver-38: #{$color-silver-38};
        --color-silver-39: #{$color-silver-39};
        --color-silver-40: #{$color-silver-40};
        --color-silver-41: #{$color-silver-41};
        --color-silver-42: #{$color-silver-42};
        --color-silver-43: #{$color-silver-43};
        --color-silver-44: #{$color-silver-44};
        --color-silver-45: #{$color-silver-45};
        --color-silver-46: #{$color-silver-46};
        --color-silver-47: #{$color-silver-47};
        --color-silver-48: #{$color-silver-48};
        --color-silver-49: #{$color-silver-49};
        --color-silver-50: #{$color-silver-50};

        --color-steel-0:  #{$color-steel-0};
        --color-steel-1:  #{$color-steel-1};
        --color-steel-2:  #{$color-steel-2};
        --color-steel-3:  #{$color-steel-3};
        --color-steel-4:  #{$color-steel-4};
        --color-steel-5:  #{$color-steel-5};
        --color-steel-6:  #{$color-steel-6};
        --color-steel-7:  #{$color-steel-7};
        --color-steel-8:  #{$color-steel-8};
        --color-steel-9:  #{$color-steel-9};
        --color-steel-10: #{$color-steel-10};
        --color-steel-11: #{$color-steel-11};
        --color-steel-12: #{$color-steel-12};
        --color-steel-13: #{$color-steel-13};
        --color-steel-14: #{$color-steel-14};
        --color-steel-15: #{$color-steel-15};
        --color-steel-16: #{$color-steel-16};
        --color-steel-17: #{$color-steel-17};
        --color-steel-18: #{$color-steel-18};
        --color-steel-19: #{$color-steel-19};
        --color-steel-20: #{$color-steel-20};
        --color-steel-21: #{$color-steel-21};
        --color-steel-22: #{$color-steel-22};
        --color-steel-23: #{$color-steel-23};
        --color-steel-24: #{$color-steel-24};
        --color-steel-25: #{$color-steel-25};
        --color-steel-26: #{$color-steel-26};
        --color-steel-27: #{$color-steel-27};
        --color-steel-28: #{$color-steel-28};
        --color-steel-29: #{$color-steel-29};
        --color-steel-30: #{$color-steel-30};
        --color-steel-31: #{$color-steel-31};
        --color-steel-32: #{$color-steel-32};
        --color-steel-33: #{$color-steel-33};
        --color-steel-34: #{$color-steel-34};
        --color-steel-35: #{$color-steel-35};
        --color-steel-36: #{$color-steel-36};
        --color-steel-37: #{$color-steel-37};
        --color-steel-38: #{$color-steel-38};
        --color-steel-39: #{$color-steel-39};
        --color-steel-40: #{$color-steel-40};
        --color-steel-41: #{$color-steel-41};
        --color-steel-42: #{$color-steel-42};
        --color-steel-43: #{$color-steel-43};
        --color-steel-44: #{$color-steel-44};
        --color-steel-45: #{$color-steel-45};
        --color-steel-46: #{$color-steel-46};
        --color-steel-47: #{$color-steel-47};
        --color-steel-48: #{$color-steel-48};
        --color-steel-49: #{$color-steel-49};
        --color-steel-50: #{$color-steel-50};

        --color-combat-0:  #{$color-combat-0};
        --color-combat-1:  #{$color-combat-1};
        --color-combat-2:  #{$color-combat-2};
        --color-combat-3:  #{$color-combat-3};
        --color-combat-4:  #{$color-combat-4};
        --color-combat-5:  #{$color-combat-5};
        --color-combat-6:  #{$color-combat-6};
        --color-combat-7:  #{$color-combat-7};
        --color-combat-8:  #{$color-combat-8};
        --color-combat-9:  #{$color-combat-9};
        --color-combat-10: #{$color-combat-10};
        --color-combat-11: #{$color-combat-11};
        --color-combat-12: #{$color-combat-12};
        --color-combat-13: #{$color-combat-13};
        --color-combat-14: #{$color-combat-14};
        --color-combat-15: #{$color-combat-15};
        --color-combat-16: #{$color-combat-16};
        --color-combat-17: #{$color-combat-17};
        --color-combat-18: #{$color-combat-18};
        --color-combat-19: #{$color-combat-19};
        --color-combat-20: #{$color-combat-20};
        --color-combat-21: #{$color-combat-21};
        --color-combat-22: #{$color-combat-22};
        --color-combat-23: #{$color-combat-23};
        --color-combat-24: #{$color-combat-24};
        --color-combat-25: #{$color-combat-25};
        --color-combat-26: #{$color-combat-26};
        --color-combat-27: #{$color-combat-27};
        --color-combat-28: #{$color-combat-28};
        --color-combat-29: #{$color-combat-29};
        --color-combat-30: #{$color-combat-30};
        --color-combat-31: #{$color-combat-31};
        --color-combat-32: #{$color-combat-32};
        --color-combat-33: #{$color-combat-33};
        --color-combat-34: #{$color-combat-34};
        --color-combat-35: #{$color-combat-35};
        --color-combat-36: #{$color-combat-36};
        --color-combat-37: #{$color-combat-37};
        --color-combat-38: #{$color-combat-38};
        --color-combat-39: #{$color-combat-39};
        --color-combat-40: #{$color-combat-40};
        --color-combat-41: #{$color-combat-41};
        --color-combat-42: #{$color-combat-42};
        --color-combat-43: #{$color-combat-43};
        --color-combat-44: #{$color-combat-44};
        --color-combat-45: #{$color-combat-45};
        --color-combat-46: #{$color-combat-46};
        --color-combat-47: #{$color-combat-47};
        --color-combat-48: #{$color-combat-48};
        --color-combat-49: #{$color-combat-49};
        --color-combat-50: #{$color-combat-50};

        --color-signs-0:  #{$color-signs-0};
        --color-signs-1:  #{$color-signs-1};
        --color-signs-2:  #{$color-signs-2};
        --color-signs-3:  #{$color-signs-3};
        --color-signs-4:  #{$color-signs-4};
        --color-signs-5:  #{$color-signs-5};
        --color-signs-6:  #{$color-signs-6};
        --color-signs-7:  #{$color-signs-7};
        --color-signs-8:  #{$color-signs-8};
        --color-signs-9:  #{$color-signs-9};
        --color-signs-10: #{$color-signs-10};
        --color-signs-11: #{$color-signs-11};
        --color-signs-12: #{$color-signs-12};
        --color-signs-13: #{$color-signs-13};
        --color-signs-14: #{$color-signs-14};
        --color-signs-15: #{$color-signs-15};
        --color-signs-16: #{$color-signs-16};
        --color-signs-17: #{$color-signs-17};
        --color-signs-18: #{$color-signs-18};
        --color-signs-19: #{$color-signs-19};
        --color-signs-20: #{$color-signs-20};
        --color-signs-21: #{$color-signs-21};
        --color-signs-22: #{$color-signs-22};
        --color-signs-23: #{$color-signs-23};
        --color-signs-24: #{$color-signs-24};
        --color-signs-25: #{$color-signs-25};
        --color-signs-26: #{$color-signs-26};
        --color-signs-27: #{$color-signs-27};
        --color-signs-28: #{$color-signs-28};
        --color-signs-29: #{$color-signs-29};
        --color-signs-30: #{$color-signs-30};
        --color-signs-31: #{$color-signs-31};
        --color-signs-32: #{$color-signs-32};
        --color-signs-33: #{$color-signs-33};
        --color-signs-34: #{$color-signs-34};
        --color-signs-35: #{$color-signs-35};
        --color-signs-36: #{$color-signs-36};
        --color-signs-37: #{$color-signs-37};
        --color-signs-38: #{$color-signs-38};
        --color-signs-39: #{$color-signs-39};
        --color-signs-40: #{$color-signs-40};
        --color-signs-41: #{$color-signs-41};
        --color-signs-42: #{$color-signs-42};
        --color-signs-43: #{$color-signs-43};
        --color-signs-44: #{$color-signs-44};
        --color-signs-45: #{$color-signs-45};
        --color-signs-46: #{$color-signs-46};
        --color-signs-47: #{$color-signs-47};
        --color-signs-48: #{$color-signs-48};
        --color-signs-49: #{$color-signs-49};
        --color-signs-50: #{$color-signs-50};

        --color-alchemy-0:  #{$color-alchemy-0};
        --color-alchemy-1:  #{$color-alchemy-1};
        --color-alchemy-2:  #{$color-alchemy-2};
        --color-alchemy-3:  #{$color-alchemy-3};
        --color-alchemy-4:  #{$color-alchemy-4};
        --color-alchemy-5:  #{$color-alchemy-5};
        --color-alchemy-6:  #{$color-alchemy-6};
        --color-alchemy-7:  #{$color-alchemy-7};
        --color-alchemy-8:  #{$color-alchemy-8};
        --color-alchemy-9:  #{$color-alchemy-9};
        --color-alchemy-10: #{$color-alchemy-10};
        --color-alchemy-11: #{$color-alchemy-11};
        --color-alchemy-12: #{$color-alchemy-12};
        --color-alchemy-13: #{$color-alchemy-13};
        --color-alchemy-14: #{$color-alchemy-14};
        --color-alchemy-15: #{$color-alchemy-15};
        --color-alchemy-16: #{$color-alchemy-16};
        --color-alchemy-17: #{$color-alchemy-17};
        --color-alchemy-18: #{$color-alchemy-18};
        --color-alchemy-19: #{$color-alchemy-19};
        --color-alchemy-20: #{$color-alchemy-20};
        --color-alchemy-21: #{$color-alchemy-21};
        --color-alchemy-22: #{$color-alchemy-22};
        --color-alchemy-23: #{$color-alchemy-23};
        --color-alchemy-24: #{$color-alchemy-24};
        --color-alchemy-25: #{$color-alchemy-25};
        --color-alchemy-26: #{$color-alchemy-26};
        --color-alchemy-27: #{$color-alchemy-27};
        --color-alchemy-28: #{$color-alchemy-28};
        --color-alchemy-29: #{$color-alchemy-29};
        --color-alchemy-30: #{$color-alchemy-30};
        --color-alchemy-31: #{$color-alchemy-31};
        --color-alchemy-32: #{$color-alchemy-32};
        --color-alchemy-33: #{$color-alchemy-33};
        --color-alchemy-34: #{$color-alchemy-34};
        --color-alchemy-35: #{$color-alchemy-35};
        --color-alchemy-36: #{$color-alchemy-36};
        --color-alchemy-37: #{$color-alchemy-37};
        --color-alchemy-38: #{$color-alchemy-38};
        --color-alchemy-39: #{$color-alchemy-39};
        --color-alchemy-40: #{$color-alchemy-40};
        --color-alchemy-41: #{$color-alchemy-41};
        --color-alchemy-42: #{$color-alchemy-42};
        --color-alchemy-43: #{$color-alchemy-43};
        --color-alchemy-44: #{$color-alchemy-44};
        --color-alchemy-45: #{$color-alchemy-45};
        --color-alchemy-46: #{$color-alchemy-46};
        --color-alchemy-47: #{$color-alchemy-47};
        --color-alchemy-48: #{$color-alchemy-48};
        --color-alchemy-49: #{$color-alchemy-49};
        --color-alchemy-50: #{$color-alchemy-50};

        --color-general-0:  #{$color-general-0};
        --color-general-1:  #{$color-general-1};
        --color-general-2:  #{$color-general-2};
        --color-general-3:  #{$color-general-3};
        --color-general-4:  #{$color-general-4};
        --color-general-5:  #{$color-general-5};
        --color-general-6:  #{$color-general-6};
        --color-general-7:  #{$color-general-7};
        --color-general-8:  #{$color-general-8};
        --color-general-9:  #{$color-general-9};
        --color-general-10: #{$color-general-10};
        --color-general-11: #{$color-general-11};
        --color-general-12: #{$color-general-12};
        --color-general-13: #{$color-general-13};
        --color-general-14: #{$color-general-14};
        --color-general-15: #{$color-general-15};
        --color-general-16: #{$color-general-16};
        --color-general-17: #{$color-general-17};
        --color-general-18: #{$color-general-18};
        --color-general-19: #{$color-general-19};
        --color-general-20: #{$color-general-20};
        --color-general-21: #{$color-general-21};
        --color-general-22: #{$color-general-22};
        --color-general-23: #{$color-general-23};
        --color-general-24: #{$color-general-24};
        --color-general-25: #{$color-general-25};
        --color-general-26: #{$color-general-26};
        --color-general-27: #{$color-general-27};
        --color-general-28: #{$color-general-28};
        --color-general-29: #{$color-general-29};
        --color-general-30: #{$color-general-30};
        --color-general-31: #{$color-general-31};
        --color-general-32: #{$color-general-32};
        --color-general-33: #{$color-general-33};
        --color-general-34: #{$color-general-34};
        --color-general-35: #{$color-general-35};
        --color-general-36: #{$color-general-36};
        --color-general-37: #{$color-general-37};
        --color-general-38: #{$color-general-38};
        --color-general-39: #{$color-general-39};
        --color-general-40: #{$color-general-40};
        --color-general-41: #{$color-general-41};
        --color-general-42: #{$color-general-42};
        --color-general-43: #{$color-general-43};
        --color-general-44: #{$color-general-44};
        --color-general-45: #{$color-general-45};
        --color-general-46: #{$color-general-46};
        --color-general-47: #{$color-general-47};
        --color-general-48: #{$color-general-48};
        --color-general-49: #{$color-general-49};
        --color-general-50: #{$color-general-50};

        --color-mutations-0:  #{$color-mutations-0};
        --color-mutations-1:  #{$color-mutations-1};
        --color-mutations-2:  #{$color-mutations-2};
        --color-mutations-3:  #{$color-mutations-3};
        --color-mutations-4:  #{$color-mutations-4};
        --color-mutations-5:  #{$color-mutations-5};
        --color-mutations-6:  #{$color-mutations-6};
        --color-mutations-7:  #{$color-mutations-7};
        --color-mutations-8:  #{$color-mutations-8};
        --color-mutations-9:  #{$color-mutations-9};
        --color-mutations-10: #{$color-mutations-10};
        --color-mutations-11: #{$color-mutations-11};
        --color-mutations-12: #{$color-mutations-12};
        --color-mutations-13: #{$color-mutations-13};
        --color-mutations-14: #{$color-mutations-14};
        --color-mutations-15: #{$color-mutations-15};
        --color-mutations-16: #{$color-mutations-16};
        --color-mutations-17: #{$color-mutations-17};
        --color-mutations-18: #{$color-mutations-18};
        --color-mutations-19: #{$color-mutations-19};
        --color-mutations-20: #{$color-mutations-20};
        --color-mutations-21: #{$color-mutations-21};
        --color-mutations-22: #{$color-mutations-22};
        --color-mutations-23: #{$color-mutations-23};
        --color-mutations-24: #{$color-mutations-24};
        --color-mutations-25: #{$color-mutations-25};
        --color-mutations-26: #{$color-mutations-26};
        --color-mutations-27: #{$color-mutations-27};
        --color-mutations-28: #{$color-mutations-28};
        --color-mutations-29: #{$color-mutations-29};
        --color-mutations-30: #{$color-mutations-30};
        --color-mutations-31: #{$color-mutations-31};
        --color-mutations-32: #{$color-mutations-32};
        --color-mutations-33: #{$color-mutations-33};
        --color-mutations-34: #{$color-mutations-34};
        --color-mutations-35: #{$color-mutations-35};
        --color-mutations-36: #{$color-mutations-36};
        --color-mutations-37: #{$color-mutations-37};
        --color-mutations-38: #{$color-mutations-38};
        --color-mutations-39: #{$color-mutations-39};
        --color-mutations-40: #{$color-mutations-40};
        --color-mutations-41: #{$color-mutations-41};
        --color-mutations-42: #{$color-mutations-42};
        --color-mutations-43: #{$color-mutations-43};
        --color-mutations-44: #{$color-mutations-44};
        --color-mutations-45: #{$color-mutations-45};
        --color-mutations-46: #{$color-mutations-46};
        --color-mutations-47: #{$color-mutations-47};
        --color-mutations-48: #{$color-mutations-48};
        --color-mutations-49: #{$color-mutations-49};
        --color-mutations-50: #{$color-mutations-50};
    }

	:global(.silver) {
		--color-key-0:  var(--color-silver-0);
		--color-key-1:  var(--color-silver-1);
		--color-key-2:  var(--color-silver-2);
		--color-key-3:  var(--color-silver-3);
		--color-key-4:  var(--color-silver-4);
		--color-key-5:  var(--color-silver-5);
		--color-key-6:  var(--color-silver-6);
		--color-key-7:  var(--color-silver-7);
		--color-key-8:  var(--color-silver-8);
		--color-key-9:  var(--color-silver-9);
		--color-key-10: var(--color-silver-10);
		--color-key-11: var(--color-silver-11);
		--color-key-12: var(--color-silver-12);
		--color-key-13: var(--color-silver-13);
		--color-key-14: var(--color-silver-14);
		--color-key-15: var(--color-silver-15);
		--color-key-16: var(--color-silver-16);
		--color-key-17: var(--color-silver-17);
		--color-key-18: var(--color-silver-18);
		--color-key-19: var(--color-silver-19);
		--color-key-20: var(--color-silver-20);
		--color-key-21: var(--color-silver-21);
		--color-key-22: var(--color-silver-22);
		--color-key-23: var(--color-silver-23);
		--color-key-24: var(--color-silver-24);
		--color-key-25: var(--color-silver-25);
		--color-key-26: var(--color-silver-26);
		--color-key-27: var(--color-silver-27);
		--color-key-28: var(--color-silver-28);
		--color-key-29: var(--color-silver-29);
		--color-key-30: var(--color-silver-30);
		--color-key-31: var(--color-silver-31);
		--color-key-32: var(--color-silver-32);
		--color-key-33: var(--color-silver-33);
		--color-key-34: var(--color-silver-34);
		--color-key-35: var(--color-silver-35);
		--color-key-36: var(--color-silver-36);
		--color-key-37: var(--color-silver-37);
		--color-key-38: var(--color-silver-38);
		--color-key-39: var(--color-silver-39);
		--color-key-40: var(--color-silver-40);
		--color-key-41: var(--color-silver-41);
		--color-key-42: var(--color-silver-42);
		--color-key-43: var(--color-silver-43);
		--color-key-44: var(--color-silver-44);
		--color-key-45: var(--color-silver-45);
		--color-key-46: var(--color-silver-46);
		--color-key-47: var(--color-silver-47);
		--color-key-48: var(--color-silver-48);
		--color-key-49: var(--color-silver-49);
		--color-key-50: var(--color-silver-50);
	}
	:global(.steel) {
		--color-key-0:  var(--color-steel-0);
		--color-key-1:  var(--color-steel-1);
		--color-key-2:  var(--color-steel-2);
		--color-key-3:  var(--color-steel-3);
		--color-key-4:  var(--color-steel-4);
		--color-key-5:  var(--color-steel-5);
		--color-key-6:  var(--color-steel-6);
		--color-key-7:  var(--color-steel-7);
		--color-key-8:  var(--color-steel-8);
		--color-key-9:  var(--color-steel-9);
		--color-key-10: var(--color-steel-10);
		--color-key-11: var(--color-steel-11);
		--color-key-12: var(--color-steel-12);
		--color-key-13: var(--color-steel-13);
		--color-key-14: var(--color-steel-14);
		--color-key-15: var(--color-steel-15);
		--color-key-16: var(--color-steel-16);
		--color-key-17: var(--color-steel-17);
		--color-key-18: var(--color-steel-18);
		--color-key-19: var(--color-steel-19);
		--color-key-20: var(--color-steel-20);
		--color-key-21: var(--color-steel-21);
		--color-key-22: var(--color-steel-22);
		--color-key-23: var(--color-steel-23);
		--color-key-24: var(--color-steel-24);
		--color-key-25: var(--color-steel-25);
		--color-key-26: var(--color-steel-26);
		--color-key-27: var(--color-steel-27);
		--color-key-28: var(--color-steel-28);
		--color-key-29: var(--color-steel-29);
		--color-key-30: var(--color-steel-30);
		--color-key-31: var(--color-steel-31);
		--color-key-32: var(--color-steel-32);
		--color-key-33: var(--color-steel-33);
		--color-key-34: var(--color-steel-34);
		--color-key-35: var(--color-steel-35);
		--color-key-36: var(--color-steel-36);
		--color-key-37: var(--color-steel-37);
		--color-key-38: var(--color-steel-38);
		--color-key-39: var(--color-steel-39);
		--color-key-40: var(--color-steel-40);
		--color-key-41: var(--color-steel-41);
		--color-key-42: var(--color-steel-42);
		--color-key-43: var(--color-steel-43);
		--color-key-44: var(--color-steel-44);
		--color-key-45: var(--color-steel-45);
		--color-key-46: var(--color-steel-46);
		--color-key-47: var(--color-steel-47);
		--color-key-48: var(--color-steel-48);
		--color-key-49: var(--color-steel-49);
		--color-key-50: var(--color-steel-50);
	}
	:global(.combat) {
		--color-key-0:  var(--color-combat-0);
		--color-key-1:  var(--color-combat-1);
		--color-key-2:  var(--color-combat-2);
		--color-key-3:  var(--color-combat-3);
		--color-key-4:  var(--color-combat-4);
		--color-key-5:  var(--color-combat-5);
		--color-key-6:  var(--color-combat-6);
		--color-key-7:  var(--color-combat-7);
		--color-key-8:  var(--color-combat-8);
		--color-key-9:  var(--color-combat-9);
		--color-key-10: var(--color-combat-10);
		--color-key-11: var(--color-combat-11);
		--color-key-12: var(--color-combat-12);
		--color-key-13: var(--color-combat-13);
		--color-key-14: var(--color-combat-14);
		--color-key-15: var(--color-combat-15);
		--color-key-16: var(--color-combat-16);
		--color-key-17: var(--color-combat-17);
		--color-key-18: var(--color-combat-18);
		--color-key-19: var(--color-combat-19);
		--color-key-20: var(--color-combat-20);
		--color-key-21: var(--color-combat-21);
		--color-key-22: var(--color-combat-22);
		--color-key-23: var(--color-combat-23);
		--color-key-24: var(--color-combat-24);
		--color-key-25: var(--color-combat-25);
		--color-key-26: var(--color-combat-26);
		--color-key-27: var(--color-combat-27);
		--color-key-28: var(--color-combat-28);
		--color-key-29: var(--color-combat-29);
		--color-key-30: var(--color-combat-30);
		--color-key-31: var(--color-combat-31);
		--color-key-32: var(--color-combat-32);
		--color-key-33: var(--color-combat-33);
		--color-key-34: var(--color-combat-34);
		--color-key-35: var(--color-combat-35);
		--color-key-36: var(--color-combat-36);
		--color-key-37: var(--color-combat-37);
		--color-key-38: var(--color-combat-38);
		--color-key-39: var(--color-combat-39);
		--color-key-40: var(--color-combat-40);
		--color-key-41: var(--color-combat-41);
		--color-key-42: var(--color-combat-42);
		--color-key-43: var(--color-combat-43);
		--color-key-44: var(--color-combat-44);
		--color-key-45: var(--color-combat-45);
		--color-key-46: var(--color-combat-46);
		--color-key-47: var(--color-combat-47);
		--color-key-48: var(--color-combat-48);
		--color-key-49: var(--color-combat-49);
		--color-key-50: var(--color-combat-50);
	}
	:global(.signs) {
		--color-key-0:  var(--color-signs-0);
		--color-key-1:  var(--color-signs-1);
		--color-key-2:  var(--color-signs-2);
		--color-key-3:  var(--color-signs-3);
		--color-key-4:  var(--color-signs-4);
		--color-key-5:  var(--color-signs-5);
		--color-key-6:  var(--color-signs-6);
		--color-key-7:  var(--color-signs-7);
		--color-key-8:  var(--color-signs-8);
		--color-key-9:  var(--color-signs-9);
		--color-key-10: var(--color-signs-10);
		--color-key-11: var(--color-signs-11);
		--color-key-12: var(--color-signs-12);
		--color-key-13: var(--color-signs-13);
		--color-key-14: var(--color-signs-14);
		--color-key-15: var(--color-signs-15);
		--color-key-16: var(--color-signs-16);
		--color-key-17: var(--color-signs-17);
		--color-key-18: var(--color-signs-18);
		--color-key-19: var(--color-signs-19);
		--color-key-20: var(--color-signs-20);
		--color-key-21: var(--color-signs-21);
		--color-key-22: var(--color-signs-22);
		--color-key-23: var(--color-signs-23);
		--color-key-24: var(--color-signs-24);
		--color-key-25: var(--color-signs-25);
		--color-key-26: var(--color-signs-26);
		--color-key-27: var(--color-signs-27);
		--color-key-28: var(--color-signs-28);
		--color-key-29: var(--color-signs-29);
		--color-key-30: var(--color-signs-30);
		--color-key-31: var(--color-signs-31);
		--color-key-32: var(--color-signs-32);
		--color-key-33: var(--color-signs-33);
		--color-key-34: var(--color-signs-34);
		--color-key-35: var(--color-signs-35);
		--color-key-36: var(--color-signs-36);
		--color-key-37: var(--color-signs-37);
		--color-key-38: var(--color-signs-38);
		--color-key-39: var(--color-signs-39);
		--color-key-40: var(--color-signs-40);
		--color-key-41: var(--color-signs-41);
		--color-key-42: var(--color-signs-42);
		--color-key-43: var(--color-signs-43);
		--color-key-44: var(--color-signs-44);
		--color-key-45: var(--color-signs-45);
		--color-key-46: var(--color-signs-46);
		--color-key-47: var(--color-signs-47);
		--color-key-48: var(--color-signs-48);
		--color-key-49: var(--color-signs-49);
		--color-key-50: var(--color-signs-50);
	}
	:global(.alchemy) {
		--color-key-0:  var(--color-alchemy-0);
		--color-key-1:  var(--color-alchemy-1);
		--color-key-2:  var(--color-alchemy-2);
		--color-key-3:  var(--color-alchemy-3);
		--color-key-4:  var(--color-alchemy-4);
		--color-key-5:  var(--color-alchemy-5);
		--color-key-6:  var(--color-alchemy-6);
		--color-key-7:  var(--color-alchemy-7);
		--color-key-8:  var(--color-alchemy-8);
		--color-key-9:  var(--color-alchemy-9);
		--color-key-10: var(--color-alchemy-10);
		--color-key-11: var(--color-alchemy-11);
		--color-key-12: var(--color-alchemy-12);
		--color-key-13: var(--color-alchemy-13);
		--color-key-14: var(--color-alchemy-14);
		--color-key-15: var(--color-alchemy-15);
		--color-key-16: var(--color-alchemy-16);
		--color-key-17: var(--color-alchemy-17);
		--color-key-18: var(--color-alchemy-18);
		--color-key-19: var(--color-alchemy-19);
		--color-key-20: var(--color-alchemy-20);
		--color-key-21: var(--color-alchemy-21);
		--color-key-22: var(--color-alchemy-22);
		--color-key-23: var(--color-alchemy-23);
		--color-key-24: var(--color-alchemy-24);
		--color-key-25: var(--color-alchemy-25);
		--color-key-26: var(--color-alchemy-26);
		--color-key-27: var(--color-alchemy-27);
		--color-key-28: var(--color-alchemy-28);
		--color-key-29: var(--color-alchemy-29);
		--color-key-30: var(--color-alchemy-30);
		--color-key-31: var(--color-alchemy-31);
		--color-key-32: var(--color-alchemy-32);
		--color-key-33: var(--color-alchemy-33);
		--color-key-34: var(--color-alchemy-34);
		--color-key-35: var(--color-alchemy-35);
		--color-key-36: var(--color-alchemy-36);
		--color-key-37: var(--color-alchemy-37);
		--color-key-38: var(--color-alchemy-38);
		--color-key-39: var(--color-alchemy-39);
		--color-key-40: var(--color-alchemy-40);
		--color-key-41: var(--color-alchemy-41);
		--color-key-42: var(--color-alchemy-42);
		--color-key-43: var(--color-alchemy-43);
		--color-key-44: var(--color-alchemy-44);
		--color-key-45: var(--color-alchemy-45);
		--color-key-46: var(--color-alchemy-46);
		--color-key-47: var(--color-alchemy-47);
		--color-key-48: var(--color-alchemy-48);
		--color-key-49: var(--color-alchemy-49);
		--color-key-50: var(--color-alchemy-50);
	}
	:global(.general) {
		--color-key-0:  var(--color-general-0);
		--color-key-1:  var(--color-general-1);
		--color-key-2:  var(--color-general-2);
		--color-key-3:  var(--color-general-3);
		--color-key-4:  var(--color-general-4);
		--color-key-5:  var(--color-general-5);
		--color-key-6:  var(--color-general-6);
		--color-key-7:  var(--color-general-7);
		--color-key-8:  var(--color-general-8);
		--color-key-9:  var(--color-general-9);
		--color-key-10: var(--color-general-10);
		--color-key-11: var(--color-general-11);
		--color-key-12: var(--color-general-12);
		--color-key-13: var(--color-general-13);
		--color-key-14: var(--color-general-14);
		--color-key-15: var(--color-general-15);
		--color-key-16: var(--color-general-16);
		--color-key-17: var(--color-general-17);
		--color-key-18: var(--color-general-18);
		--color-key-19: var(--color-general-19);
		--color-key-20: var(--color-general-20);
		--color-key-21: var(--color-general-21);
		--color-key-22: var(--color-general-22);
		--color-key-23: var(--color-general-23);
		--color-key-24: var(--color-general-24);
		--color-key-25: var(--color-general-25);
		--color-key-26: var(--color-general-26);
		--color-key-27: var(--color-general-27);
		--color-key-28: var(--color-general-28);
		--color-key-29: var(--color-general-29);
		--color-key-30: var(--color-general-30);
		--color-key-31: var(--color-general-31);
		--color-key-32: var(--color-general-32);
		--color-key-33: var(--color-general-33);
		--color-key-34: var(--color-general-34);
		--color-key-35: var(--color-general-35);
		--color-key-36: var(--color-general-36);
		--color-key-37: var(--color-general-37);
		--color-key-38: var(--color-general-38);
		--color-key-39: var(--color-general-39);
		--color-key-40: var(--color-general-40);
		--color-key-41: var(--color-general-41);
		--color-key-42: var(--color-general-42);
		--color-key-43: var(--color-general-43);
		--color-key-44: var(--color-general-44);
		--color-key-45: var(--color-general-45);
		--color-key-46: var(--color-general-46);
		--color-key-47: var(--color-general-47);
		--color-key-48: var(--color-general-48);
		--color-key-49: var(--color-general-49);
		--color-key-50: var(--color-general-50);
	}
    
	:global(.alchemy.combat) {}
	:global(.alchemy.signs) {}
	:global(.combat.signs) {}
	:global(.mutations) {
		--color-key-0:  var(--color-mutations-0);
		--color-key-1:  var(--color-mutations-1);
		--color-key-2:  var(--color-mutations-2);
		--color-key-3:  var(--color-mutations-3);
		--color-key-4:  var(--color-mutations-4);
		--color-key-5:  var(--color-mutations-5);
		--color-key-6:  var(--color-mutations-6);
		--color-key-7:  var(--color-mutations-7);
		--color-key-8:  var(--color-mutations-8);
		--color-key-9:  var(--color-mutations-9);
		--color-key-10: var(--color-mutations-10);
		--color-key-11: var(--color-mutations-11);
		--color-key-12: var(--color-mutations-12);
		--color-key-13: var(--color-mutations-13);
		--color-key-14: var(--color-mutations-14);
		--color-key-15: var(--color-mutations-15);
		--color-key-16: var(--color-mutations-16);
		--color-key-17: var(--color-mutations-17);
		--color-key-18: var(--color-mutations-18);
		--color-key-19: var(--color-mutations-19);
		--color-key-20: var(--color-mutations-20);
		--color-key-21: var(--color-mutations-21);
		--color-key-22: var(--color-mutations-22);
		--color-key-23: var(--color-mutations-23);
		--color-key-24: var(--color-mutations-24);
		--color-key-25: var(--color-mutations-25);
		--color-key-26: var(--color-mutations-26);
		--color-key-27: var(--color-mutations-27);
		--color-key-28: var(--color-mutations-28);
		--color-key-29: var(--color-mutations-29);
		--color-key-30: var(--color-mutations-30);
		--color-key-31: var(--color-mutations-31);
		--color-key-32: var(--color-mutations-32);
		--color-key-33: var(--color-mutations-33);
		--color-key-34: var(--color-mutations-34);
		--color-key-35: var(--color-mutations-35);
		--color-key-36: var(--color-mutations-36);
		--color-key-37: var(--color-mutations-37);
		--color-key-38: var(--color-mutations-38);
		--color-key-39: var(--color-mutations-39);
		--color-key-40: var(--color-mutations-40);
		--color-key-41: var(--color-mutations-41);
		--color-key-42: var(--color-mutations-42);
		--color-key-43: var(--color-mutations-43);
		--color-key-44: var(--color-mutations-44);
		--color-key-45: var(--color-mutations-45);
		--color-key-46: var(--color-mutations-46);
		--color-key-47: var(--color-mutations-47);
		--color-key-48: var(--color-mutations-48);
		--color-key-49: var(--color-mutations-49);
		--color-key-50: var(--color-mutations-50);
	}
	:global(.shadow) {
		filter: drop-shadow(0px 1px 1px var(--color-key-9));
	}
	:global(.shadowText) {
		text-shadow: 0 1px 3px var(--color-key-12);
	}
	:global(.tooltip) {
        pointer-events: none;
        width: max-content;
        position: absolute;
        top: anchor(100%);
        left: anchor(50%);
        translate: -50%;
        box-shadow: 0 2px 8px 1px var(--color-grey-22);
        color: black;
        border: 2px solid oklch(from var(--color-key-1) l calc(c * 0.15) h);
        border-radius: 8px;
        padding: 1em;
		overflow: visible;
		background:	linear-gradient(in oklab to bottom, white, transparent),
					linear-gradient(in oklab to right, 
						oklch(from var(--color-key-1) l c h / 0.125), 
						oklch(from var(--color-key-0) l c h / 0.125) 44% 56%, 
						oklch(from var(--color-key-1) l c h / 0.125)),
					white;

        &::before, &::after {
            content: "";
            position: absolute;
            left: 50%;
            translate: -50%;
            rotate: 45deg;
            width: 12px;
            height: 12px;
        }
        &::before {
            top: calc((-12px * (1 / 2)) - 2px);
			background-color: oklch(from var(--color-key-1) l calc(c * 0.15) h);
        }
        &::after {
            top: calc((-12px * (1 / 2)) + (2px * (sqrt(2) - 1)));
			background: white;
        }
	}

    .frameKits {
        background-color: teal;
        overflow-y: auto;
        height: 100%;
        display: flex;
        flex-flow: column nowrap;
        /* align-content: stretch; */
        /* align-items: stretch; */
        /* justify-content: stretch; */
        /* justify-items: stretch; */
    }

    .gearAndStats {
        display: grid;
        grid-template-columns: repeat(8, max-content);
        grid-template-rows: max-content;
        grid-auto-rows: minmax(0, 1fr);
        /* gap: 0px 1px; */
        /* align-content: stretch; */
        /* align-items: stretch; */
        /* justify-content: stretch; */
        /* justify-items: stretch; */
    }

    .statsWrapper {
        grid-column: 1 / -1;
        overflow-y: auto;
        display: grid;
        grid-template-columns: subgrid;
    }
</style>